<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class CountriesController extends Controller
{
    /**
     * Obtiene la lista de países con códigos de teléfono
     */
    public function index(): JsonResponse
    {
        $countries = [
            ['code' => 'AD', 'name' => 'Andorra', 'phone_code' => '+376'],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'phone_code' => '+971'],
            ['code' => 'AF', 'name' => 'Afghanistan', 'phone_code' => '+93'],
            ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'phone_code' => '+1268'],
            ['code' => 'AI', 'name' => 'Anguilla', 'phone_code' => '+1264'],
            ['code' => 'AL', 'name' => 'Albania', 'phone_code' => '+355'],
            ['code' => 'AM', 'name' => 'Armenia', 'phone_code' => '+374'],
            ['code' => 'AO', 'name' => 'Angola', 'phone_code' => '+244'],
            ['code' => 'AQ', 'name' => 'Antarctica', 'phone_code' => '+672'],
            ['code' => 'AR', 'name' => 'Argentina', 'phone_code' => '+54'],
            ['code' => 'AS', 'name' => 'American Samoa', 'phone_code' => '+1684'],
            ['code' => 'AT', 'name' => 'Austria', 'phone_code' => '+43'],
            ['code' => 'AU', 'name' => 'Australia', 'phone_code' => '+61'],
            ['code' => 'AW', 'name' => 'Aruba', 'phone_code' => '+297'],
            ['code' => 'AX', 'name' => 'Åland Islands', 'phone_code' => '+358'],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'phone_code' => '+994'],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'phone_code' => '+387'],
            ['code' => 'BB', 'name' => 'Barbados', 'phone_code' => '+1246'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'phone_code' => '+880'],
            ['code' => 'BE', 'name' => 'Belgium', 'phone_code' => '+32'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'phone_code' => '+226'],
            ['code' => 'BG', 'name' => 'Bulgaria', 'phone_code' => '+359'],
            ['code' => 'BH', 'name' => 'Bahrain', 'phone_code' => '+973'],
            ['code' => 'BI', 'name' => 'Burundi', 'phone_code' => '+257'],
            ['code' => 'BJ', 'name' => 'Benin', 'phone_code' => '+229'],
            ['code' => 'BL', 'name' => 'Saint Barthélemy', 'phone_code' => '+590'],
            ['code' => 'BM', 'name' => 'Bermuda', 'phone_code' => '+1441'],
            ['code' => 'BN', 'name' => 'Brunei', 'phone_code' => '+673'],
            ['code' => 'BO', 'name' => 'Bolivia', 'phone_code' => '+591'],
            ['code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius and Saba', 'phone_code' => '+599'],
            ['code' => 'BR', 'name' => 'Brazil', 'phone_code' => '+55'],
            ['code' => 'BS', 'name' => 'Bahamas', 'phone_code' => '+1242'],
            ['code' => 'BT', 'name' => 'Bhutan', 'phone_code' => '+975'],
            ['code' => 'BV', 'name' => 'Bouvet Island', 'phone_code' => '+47'],
            ['code' => 'BW', 'name' => 'Botswana', 'phone_code' => '+267'],
            ['code' => 'BY', 'name' => 'Belarus', 'phone_code' => '+375'],
            ['code' => 'BZ', 'name' => 'Belize', 'phone_code' => '+501'],
            ['code' => 'CA', 'name' => 'Canada', 'phone_code' => '+1'],
            ['code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'phone_code' => '+61'],
            ['code' => 'CD', 'name' => 'Democratic Republic of the Congo', 'phone_code' => '+243'],
            ['code' => 'CF', 'name' => 'Central African Republic', 'phone_code' => '+236'],
            ['code' => 'CG', 'name' => 'Congo', 'phone_code' => '+242'],
            ['code' => 'CH', 'name' => 'Switzerland', 'phone_code' => '+41'],
            ['code' => 'CI', 'name' => 'Ivory Coast', 'phone_code' => '+225'],
            ['code' => 'CK', 'name' => 'Cook Islands', 'phone_code' => '+682'],
            ['code' => 'CL', 'name' => 'Chile', 'phone_code' => '+56'],
            ['code' => 'CM', 'name' => 'Cameroon', 'phone_code' => '+237'],
            ['code' => 'CN', 'name' => 'China', 'phone_code' => '+86'],
            ['code' => 'CO', 'name' => 'Colombia', 'phone_code' => '+57'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'phone_code' => '+506'],
            ['code' => 'CU', 'name' => 'Cuba', 'phone_code' => '+53'],
            ['code' => 'CV', 'name' => 'Cape Verde', 'phone_code' => '+238'],
            ['code' => 'CW', 'name' => 'Curaçao', 'phone_code' => '+599'],
            ['code' => 'CX', 'name' => 'Christmas Island', 'phone_code' => '+61'],
            ['code' => 'CY', 'name' => 'Cyprus', 'phone_code' => '+357'],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'phone_code' => '+420'],
            ['code' => 'DE', 'name' => 'Germany', 'phone_code' => '+49'],
            ['code' => 'DJ', 'name' => 'Djibouti', 'phone_code' => '+253'],
            ['code' => 'DK', 'name' => 'Denmark', 'phone_code' => '+45'],
            ['code' => 'DM', 'name' => 'Dominica', 'phone_code' => '+1767'],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'phone_code' => '+1'],
            ['code' => 'DZ', 'name' => 'Algeria', 'phone_code' => '+213'],
            ['code' => 'EC', 'name' => 'Ecuador', 'phone_code' => '+593'],
            ['code' => 'EE', 'name' => 'Estonia', 'phone_code' => '+372'],
            ['code' => 'EG', 'name' => 'Egypt', 'phone_code' => '+20'],
            ['code' => 'EH', 'name' => 'Western Sahara', 'phone_code' => '+212'],
            ['code' => 'ER', 'name' => 'Eritrea', 'phone_code' => '+291'],
            ['code' => 'ES', 'name' => 'Spain', 'phone_code' => '+34'],
            ['code' => 'ET', 'name' => 'Ethiopia', 'phone_code' => '+251'],
            ['code' => 'FI', 'name' => 'Finlandia', 'phone_code' => '+358'],
            ['code' => 'FJ', 'name' => 'Fiji', 'phone_code' => '+679'],
            ['code' => 'FK', 'name' => 'Falkland Islands', 'phone_code' => '+500'],
            ['code' => 'FM', 'name' => 'Micronesia', 'phone_code' => '+691'],
            ['code' => 'FO', 'name' => 'Faroe Islands', 'phone_code' => '+298'],
            ['code' => 'FR', 'name' => 'France', 'phone_code' => '+33'],
            ['code' => 'GA', 'name' => 'Gabon', 'phone_code' => '+241'],
            ['code' => 'GB', 'name' => 'United Kingdom', 'phone_code' => '+44'],
            ['code' => 'GD', 'name' => 'Grenada', 'phone_code' => '+1473'],
            ['code' => 'GE', 'name' => 'Georgia', 'phone_code' => '+995'],
            ['code' => 'GF', 'name' => 'French Guiana', 'phone_code' => '+594'],
            ['code' => 'GG', 'name' => 'Guernsey', 'phone_code' => '+44'],
            ['code' => 'GH', 'name' => 'Ghana', 'phone_code' => '+233'],
            ['code' => 'GI', 'name' => 'Gibraltar', 'phone_code' => '+350'],
            ['code' => 'GL', 'name' => 'Greenland', 'phone_code' => '+299'],
            ['code' => 'GM', 'name' => 'Gambia', 'phone_code' => '+220'],
            ['code' => 'GN', 'name' => 'Guinea', 'phone_code' => '+224'],
            ['code' => 'GP', 'name' => 'Guadeloupe', 'phone_code' => '+590'],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'phone_code' => '+240'],
            ['code' => 'GR', 'name' => 'Greece', 'phone_code' => '+30'],
            ['code' => 'GS', 'name' => 'South Georgia', 'phone_code' => '+500'],
            ['code' => 'GT', 'name' => 'Guatemala', 'phone_code' => '+502'],
            ['code' => 'GU', 'name' => 'Guam', 'phone_code' => '+1671'],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'phone_code' => '+245'],
            ['code' => 'GY', 'name' => 'Guyana', 'phone_code' => '+592'],
            ['code' => 'HK', 'name' => 'Hong Kong', 'phone_code' => '+852'],
            ['code' => 'HM', 'name' => 'Heard Island', 'phone_code' => '+672'],
            ['code' => 'HN', 'name' => 'Honduras', 'phone_code' => '+504'],
            ['code' => 'HR', 'name' => 'Croatia', 'phone_code' => '+385'],
            ['code' => 'HT', 'name' => 'Haiti', 'phone_code' => '+509'],
            ['code' => 'HU', 'name' => 'Hungary', 'phone_code' => '+36'],
            ['code' => 'ID', 'name' => 'Indonesia', 'phone_code' => '+62'],
            ['code' => 'IE', 'name' => 'Ireland', 'phone_code' => '+353'],
            ['code' => 'IL', 'name' => 'Israel', 'phone_code' => '+972'],
            ['code' => 'IM', 'name' => 'Isle of Man', 'phone_code' => '+44'],
            ['code' => 'IN', 'name' => 'India', 'phone_code' => '+91'],
            ['code' => 'IO', 'name' => 'British Indian Ocean Territory', 'phone_code' => '+246'],
            ['code' => 'IQ', 'name' => 'Iraq', 'phone_code' => '+964'],
            ['code' => 'IR', 'name' => 'Iran', 'phone_code' => '+98'],
            ['code' => 'IS', 'name' => 'Iceland', 'phone_code' => '+354'],
            ['code' => 'IT', 'name' => 'Italy', 'phone_code' => '+39'],
            ['code' => 'JE', 'name' => 'Jersey', 'phone_code' => '+44'],
            ['code' => 'JM', 'name' => 'Jamaica', 'phone_code' => '+1876'],
            ['code' => 'JO', 'name' => 'Jordan', 'phone_code' => '+962'],
            ['code' => 'JP', 'name' => 'Japan', 'phone_code' => '+81'],
            ['code' => 'KE', 'name' => 'Kenya', 'phone_code' => '+254'],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'phone_code' => '+996'],
            ['code' => 'KH', 'name' => 'Cambodia', 'phone_code' => '+855'],
            ['code' => 'KI', 'name' => 'Kiribati', 'phone_code' => '+686'],
            ['code' => 'KM', 'name' => 'Comoros', 'phone_code' => '+269'],
            ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'phone_code' => '+1869'],
            ['code' => 'KP', 'name' => 'North Korea', 'phone_code' => '+850'],
            ['code' => 'KR', 'name' => 'South Korea', 'phone_code' => '+82'],
            ['code' => 'KW', 'name' => 'Kuwait', 'phone_code' => '+965'],
            ['code' => 'KY', 'name' => 'Cayman Islands', 'phone_code' => '+1345'],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'phone_code' => '+7'],
            ['code' => 'LA', 'name' => 'Laos', 'phone_code' => '+856'],
            ['code' => 'LB', 'name' => 'Lebanon', 'phone_code' => '+961'],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'phone_code' => '+1758'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'phone_code' => '+423'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'phone_code' => '+94'],
            ['code' => 'LR', 'name' => 'Liberia', 'phone_code' => '+231'],
            ['code' => 'LS', 'name' => 'Lesotho', 'phone_code' => '+266'],
            ['code' => 'LT', 'name' => 'Lithuania', 'phone_code' => '+370'],
            ['code' => 'LU', 'name' => 'Luxembourg', 'phone_code' => '+352'],
            ['code' => 'LV', 'name' => 'Latvia', 'phone_code' => '+371'],
            ['code' => 'LY', 'name' => 'Libya', 'phone_code' => '+218'],
            ['code' => 'MA', 'name' => 'Morocco', 'phone_code' => '+212'],
            ['code' => 'MC', 'name' => 'Monaco', 'phone_code' => '+377'],
            ['code' => 'MD', 'name' => 'Moldova', 'phone_code' => '+373'],
            ['code' => 'ME', 'name' => 'Montenegro', 'phone_code' => '+382'],
            ['code' => 'MF', 'name' => 'Saint Martin', 'phone_code' => '+590'],
            ['code' => 'MG', 'name' => 'Madagascar', 'phone_code' => '+261'],
            ['code' => 'MH', 'name' => 'Marshall Islands', 'phone_code' => '+692'],
            ['code' => 'MK', 'name' => 'North Macedonia', 'phone_code' => '+389'],
            ['code' => 'ML', 'name' => 'Mali', 'phone_code' => '+223'],
            ['code' => 'MM', 'name' => 'Myanmar', 'phone_code' => '+95'],
            ['code' => 'MN', 'name' => 'Mongolia', 'phone_code' => '+976'],
            ['code' => 'MO', 'name' => 'Macao', 'phone_code' => '+853'],
            ['code' => 'MP', 'name' => 'Northern Mariana Islands', 'phone_code' => '+1670'],
            ['code' => 'MQ', 'name' => 'Martinique', 'phone_code' => '+596'],
            ['code' => 'MR', 'name' => 'Mauritania', 'phone_code' => '+222'],
            ['code' => 'MS', 'name' => 'Montserrat', 'phone_code' => '+1664'],
            ['code' => 'MT', 'name' => 'Malta', 'phone_code' => '+356'],
            ['code' => 'MU', 'name' => 'Mauritius', 'phone_code' => '+230'],
            ['code' => 'MV', 'name' => 'Maldives', 'phone_code' => '+960'],
            ['code' => 'MW', 'name' => 'Malawi', 'phone_code' => '+265'],
            ['code' => 'MX', 'name' => 'Mexico', 'phone_code' => '+52'],
            ['code' => 'MY', 'name' => 'Malaysia', 'phone_code' => '+60'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'phone_code' => '+258'],
            ['code' => 'NA', 'name' => 'Namibia', 'phone_code' => '+264'],
            ['code' => 'NC', 'name' => 'New Caledonia', 'phone_code' => '+687'],
            ['code' => 'NE', 'name' => 'Niger', 'phone_code' => '+227'],
            ['code' => 'NF', 'name' => 'Norfolk Island', 'phone_code' => '+672'],
            ['code' => 'NG', 'name' => 'Nigeria', 'phone_code' => '+234'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'phone_code' => '+505'],
            ['code' => 'NL', 'name' => 'Netherlands', 'phone_code' => '+31'],
            ['code' => 'NO', 'name' => 'Norway', 'phone_code' => '+47'],
            ['code' => 'NP', 'name' => 'Nepal', 'phone_code' => '+977'],
            ['code' => 'NR', 'name' => 'Nauru', 'phone_code' => '+674'],
            ['code' => 'NU', 'name' => 'Niue', 'phone_code' => '+683'],
            ['code' => 'NZ', 'name' => 'New Zealand', 'phone_code' => '+64'],
            ['code' => 'OM', 'name' => 'Oman', 'phone_code' => '+968'],
            ['code' => 'PA', 'name' => 'Panama', 'phone_code' => '+507'],
            ['code' => 'PE', 'name' => 'Peru', 'phone_code' => '+51'],
            ['code' => 'PF', 'name' => 'French Polynesia', 'phone_code' => '+689'],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'phone_code' => '+675'],
            ['code' => 'PH', 'name' => 'Philippines', 'phone_code' => '+63'],
            ['code' => 'PK', 'name' => 'Pakistan', 'phone_code' => '+92'],
            ['code' => 'PL', 'name' => 'Poland', 'phone_code' => '+48'],
            ['code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'phone_code' => '+508'],
            ['code' => 'PN', 'name' => 'Pitcairn Islands', 'phone_code' => '+64'],
            ['code' => 'PR', 'name' => 'Puerto Rico', 'phone_code' => '+1787'],
            ['code' => 'PS', 'name' => 'Palestine', 'phone_code' => '+970'],
            ['code' => 'PT', 'name' => 'Portugal', 'phone_code' => '+351'],
            ['code' => 'PW', 'name' => 'Palau', 'phone_code' => '+680'],
            ['code' => 'PY', 'name' => 'Paraguay', 'phone_code' => '+595'],
            ['code' => 'QA', 'name' => 'Qatar', 'phone_code' => '+974'],
            ['code' => 'RE', 'name' => 'Réunion', 'phone_code' => '+262'],
            ['code' => 'RO', 'name' => 'Romania', 'phone_code' => '+40'],
            ['code' => 'RS', 'name' => 'Serbia', 'phone_code' => '+381'],
            ['code' => 'RU', 'name' => 'Russia', 'phone_code' => '+7'],
            ['code' => 'RW', 'name' => 'Rwanda', 'phone_code' => '+250'],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'phone_code' => '+966'],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'phone_code' => '+677'],
            ['code' => 'SC', 'name' => 'Seychelles', 'phone_code' => '+248'],
            ['code' => 'SD', 'name' => 'Sudan', 'phone_code' => '+249'],
            ['code' => 'SE', 'name' => 'Sweden', 'phone_code' => '+46'],
            ['code' => 'SG', 'name' => 'Singapore', 'phone_code' => '+65'],
            ['code' => 'SH', 'name' => 'Saint Helena', 'phone_code' => '+290'],
            ['code' => 'SI', 'name' => 'Slovenia', 'phone_code' => '+386'],
            ['code' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'phone_code' => '+47'],
            ['code' => 'SK', 'name' => 'Slovakia', 'phone_code' => '+421'],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'phone_code' => '+232'],
            ['code' => 'SM', 'name' => 'San Marino', 'phone_code' => '+378'],
            ['code' => 'SN', 'name' => 'Senegal', 'phone_code' => '+221'],
            ['code' => 'SO', 'name' => 'Somalia', 'phone_code' => '+252'],
            ['code' => 'SR', 'name' => 'Suriname', 'phone_code' => '+597'],
            ['code' => 'SS', 'name' => 'South Sudan', 'phone_code' => '+211'],
            ['code' => 'ST', 'name' => 'São Tomé and Príncipe', 'phone_code' => '+239'],
            ['code' => 'SV', 'name' => 'El Salvador', 'phone_code' => '+503'],
            ['code' => 'SX', 'name' => 'Sint Maarten', 'phone_code' => '+1721'],
            ['code' => 'SY', 'name' => 'Syria', 'phone_code' => '+963'],
            ['code' => 'SZ', 'name' => 'Eswatini', 'phone_code' => '+268'],
            ['code' => 'TC', 'name' => 'Turks and Caicos Islands', 'phone_code' => '+1649'],
            ['code' => 'TD', 'name' => 'Chad', 'phone_code' => '+235'],
            ['code' => 'TF', 'name' => 'French Southern Territories', 'phone_code' => '+262'],
            ['code' => 'TG', 'name' => 'Togo', 'phone_code' => '+228'],
            ['code' => 'TH', 'name' => 'Thailand', 'phone_code' => '+66'],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'phone_code' => '+992'],
            ['code' => 'TK', 'name' => 'Tokelau', 'phone_code' => '+690'],
            ['code' => 'TL', 'name' => 'East Timor', 'phone_code' => '+670'],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'phone_code' => '+993'],
            ['code' => 'TN', 'name' => 'Tunisia', 'phone_code' => '+216'],
            ['code' => 'TO', 'name' => 'Tonga', 'phone_code' => '+676'],
            ['code' => 'TR', 'name' => 'Turkey', 'phone_code' => '+90'],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'phone_code' => '+1868'],
            ['code' => 'TV', 'name' => 'Tuvalu', 'phone_code' => '+688'],
            ['code' => 'TW', 'name' => 'Taiwan', 'phone_code' => '+886'],
            ['code' => 'TZ', 'name' => 'Tanzania', 'phone_code' => '+255'],
            ['code' => 'UA', 'name' => 'Ukraine', 'phone_code' => '+380'],
            ['code' => 'UG', 'name' => 'Uganda', 'phone_code' => '+256'],
            ['code' => 'UM', 'name' => 'United States Minor Outlying Islands', 'phone_code' => '+1'],
            ['code' => 'US', 'name' => 'United States', 'phone_code' => '+1'],
            ['code' => 'UY', 'name' => 'Uruguay', 'phone_code' => '+598'],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'phone_code' => '+998'],
            ['code' => 'VA', 'name' => 'Vatican City', 'phone_code' => '+39'],
            ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'phone_code' => '+1784'],
            ['code' => 'VE', 'name' => 'Venezuela', 'phone_code' => '+58'],
            ['code' => 'VG', 'name' => 'British Virgin Islands', 'phone_code' => '+1284'],
            ['code' => 'VI', 'name' => 'United States Virgin Islands', 'phone_code' => '+1340'],
            ['code' => 'VN', 'name' => 'Vietnam', 'phone_code' => '+84'],
            ['code' => 'VU', 'name' => 'Vanuatu', 'phone_code' => '+678'],
            ['code' => 'WF', 'name' => 'Wallis and Futuna', 'phone_code' => '+681'],
            ['code' => 'WS', 'name' => 'Samoa', 'phone_code' => '+685'],
            ['code' => 'YE', 'name' => 'Ymen', 'phone_code' => '+967'],
            ['code' => 'YT', 'name' => 'Mayotte', 'phone_code' => '+262'],
            ['code' => 'ZA', 'name' => 'South Africa', 'phone_code' => '+27'],
            ['code' => 'ZM', 'name' => 'Zambia', 'phone_code' => '+260'],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'phone_code' => '+263'],
        ];

        return response()->json([
            'success' => true,
            'countries' => $countries,
            'total' => count($countries)
        ]);
    }

    /**
     * Busca países por nombre o código
     */
    public function search(Request $request): JsonResponse
    {
        $query = $request->input('q', '');

        if (empty($query)) {
            return $this->index();
        }

        $allCountries = $this->index()->getData()->countries;

        $filtered = array_filter($allCountries, function($country) use ($query) {
            return stripos($country->name, $query) !== false ||
                   stripos($country->code, $query) !== false ||
                   stripos($country->phone_code, $query) !== false;
        });

        return response()->json([
            'success' => true,
            'countries' => array_values($filtered),
            'total' => count($filtered),
            'query' => $query
        ]);
    }
}
