<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class CountriesController extends Controller
{
    /**
     * Obtiene la lista de países con códigos de teléfono
     */
    public function index(): JsonResponse
    {
        $countries = [
            ['code' => 'AD', 'name' => 'Andorra', 'phone_code' => '+376'],
            ['code' => 'AE', 'name' => 'Emiratos Árabes Unidos', 'phone_code' => '+971'],
            ['code' => 'AF', 'name' => 'Afganistán', 'phone_code' => '+93'],
            ['code' => 'AG', 'name' => 'Antigua y Barbuda', 'phone_code' => '+1268'],
            ['code' => 'AI', 'name' => 'Anguila', 'phone_code' => '+1264'],
            ['code' => 'AL', 'name' => 'Albania', 'phone_code' => '+355'],
            ['code' => 'AM', 'name' => 'Armenia', 'phone_code' => '+374'],
            ['code' => 'AO', 'name' => 'Angola', 'phone_code' => '+244'],
            ['code' => 'AQ', 'name' => 'Antártida', 'phone_code' => '+672'],
            ['code' => 'AR', 'name' => 'Argentina', 'phone_code' => '+54'],
            ['code' => 'AS', 'name' => 'Samoa Americana', 'phone_code' => '+1684'],
            ['code' => 'AT', 'name' => 'Austria', 'phone_code' => '+43'],
            ['code' => 'AU', 'name' => 'Australia', 'phone_code' => '+61'],
            ['code' => 'AW', 'name' => 'Aruba', 'phone_code' => '+297'],
            ['code' => 'AX', 'name' => 'Islas Åland', 'phone_code' => '+358'],
            ['code' => 'AZ', 'name' => 'Azerbaiyán', 'phone_code' => '+994'],
            ['code' => 'BA', 'name' => 'Bosnia y Herzegovina', 'phone_code' => '+387'],
            ['code' => 'BB', 'name' => 'Barbados', 'phone_code' => '+1246'],
            ['code' => 'BD', 'name' => 'Bangladés', 'phone_code' => '+880'],
            ['code' => 'BE', 'name' => 'Bélgica', 'phone_code' => '+32'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'phone_code' => '+226'],
            ['code' => 'BG', 'name' => 'Bulgaria', 'phone_code' => '+359'],
            ['code' => 'BH', 'name' => 'Baréin', 'phone_code' => '+973'],
            ['code' => 'BI', 'name' => 'Burundi', 'phone_code' => '+257'],
            ['code' => 'BJ', 'name' => 'Benín', 'phone_code' => '+229'],
            ['code' => 'BL', 'name' => 'San Bartolomé', 'phone_code' => '+590'],
            ['code' => 'BM', 'name' => 'Bermudas', 'phone_code' => '+1441'],
            ['code' => 'BN', 'name' => 'Brunéi', 'phone_code' => '+673'],
            ['code' => 'BO', 'name' => 'Bolivia', 'phone_code' => '+591'],
            ['code' => 'BQ', 'name' => 'Bonaire, San Eustaquio y Saba', 'phone_code' => '+599'],
            ['code' => 'BR', 'name' => 'Brasil', 'phone_code' => '+55'],
            ['code' => 'BS', 'name' => 'Bahamas', 'phone_code' => '+1242'],
            ['code' => 'BT', 'name' => 'Bután', 'phone_code' => '+975'],
            ['code' => 'BV', 'name' => 'Isla Bouvet', 'phone_code' => '+47'],
            ['code' => 'BW', 'name' => 'Botsuana', 'phone_code' => '+267'],
            ['code' => 'BY', 'name' => 'Bielorrusia', 'phone_code' => '+375'],
            ['code' => 'BZ', 'name' => 'Belice', 'phone_code' => '+501'],
            ['code' => 'CA', 'name' => 'Canadá', 'phone_code' => '+1'],
            ['code' => 'CC', 'name' => 'Islas Cocos', 'phone_code' => '+61'],
            ['code' => 'CD', 'name' => 'República Democrática del Congo', 'phone_code' => '+243'],
            ['code' => 'CF', 'name' => 'República Centroafricana', 'phone_code' => '+236'],
            ['code' => 'CG', 'name' => 'Congo', 'phone_code' => '+242'],
            ['code' => 'CH', 'name' => 'Suiza', 'phone_code' => '+41'],
            ['code' => 'CI', 'name' => 'Costa de Marfil', 'phone_code' => '+225'],
            ['code' => 'CK', 'name' => 'Islas Cook', 'phone_code' => '+682'],
            ['code' => 'CL', 'name' => 'Chile', 'phone_code' => '+56'],
            ['code' => 'CM', 'name' => 'Camerún', 'phone_code' => '+237'],
            ['code' => 'CN', 'name' => 'China', 'phone_code' => '+86'],
            ['code' => 'CO', 'name' => 'Colombia', 'phone_code' => '+57'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'phone_code' => '+506'],
            ['code' => 'CU', 'name' => 'Cuba', 'phone_code' => '+53'],
            ['code' => 'CV', 'name' => 'Cabo Verde', 'phone_code' => '+238'],
            ['code' => 'CW', 'name' => 'Curazao', 'phone_code' => '+599'],
            ['code' => 'CX', 'name' => 'Isla Christmas', 'phone_code' => '+61'],
            ['code' => 'CY', 'name' => 'Chipre', 'phone_code' => '+357'],
            ['code' => 'CZ', 'name' => 'República Checa', 'phone_code' => '+420'],
            ['code' => 'DE', 'name' => 'Alemania', 'phone_code' => '+49'],
            ['code' => 'DJ', 'name' => 'Yibuti', 'phone_code' => '+253'],
            ['code' => 'DK', 'name' => 'Dinamarca', 'phone_code' => '+45'],
            ['code' => 'DM', 'name' => 'Dominica', 'phone_code' => '+1767'],
            ['code' => 'DO', 'name' => 'República Dominicana', 'phone_code' => '+1'],
            ['code' => 'DZ', 'name' => 'Argelia', 'phone_code' => '+213'],
            ['code' => 'EC', 'name' => 'Ecuador', 'phone_code' => '+593'],
            ['code' => 'EE', 'name' => 'Estonia', 'phone_code' => '+372'],
            ['code' => 'EG', 'name' => 'Egipto', 'phone_code' => '+20'],
            ['code' => 'EH', 'name' => 'Sahara Occidental', 'phone_code' => '+212'],
            ['code' => 'ER', 'name' => 'Eritrea', 'phone_code' => '+291'],
            ['code' => 'ES', 'name' => 'España', 'phone_code' => '+34'],
            ['code' => 'ET', 'name' => 'Etiopía', 'phone_code' => '+251'],
            ['code' => 'FI', 'name' => 'Finlandia', 'phone_code' => '+358'],
            ['code' => 'FJ', 'name' => 'Fiyi', 'phone_code' => '+679'],
            ['code' => 'FK', 'name' => 'Islas Malvinas', 'phone_code' => '+500'],
            ['code' => 'FM', 'name' => 'Micronesia', 'phone_code' => '+691'],
            ['code' => 'FO', 'name' => 'Islas Feroe', 'phone_code' => '+298'],
            ['code' => 'FR', 'name' => 'Francia', 'phone_code' => '+33'],
            ['code' => 'GA', 'name' => 'Gabón', 'phone_code' => '+241'],
            ['code' => 'GB', 'name' => 'Reino Unido', 'phone_code' => '+44'],
            ['code' => 'GD', 'name' => 'Granada', 'phone_code' => '+1473'],
            ['code' => 'GE', 'name' => 'Georgia', 'phone_code' => '+995'],
            ['code' => 'GF', 'name' => 'Guayana Francesa', 'phone_code' => '+594'],
            ['code' => 'GG', 'name' => 'Guernsey', 'phone_code' => '+44'],
            ['code' => 'GH', 'name' => 'Ghana', 'phone_code' => '+233'],
            ['code' => 'GI', 'name' => 'Gibraltar', 'phone_code' => '+350'],
            ['code' => 'GL', 'name' => 'Groenlandia', 'phone_code' => '+299'],
            ['code' => 'GM', 'name' => 'Gambia', 'phone_code' => '+220'],
            ['code' => 'GN', 'name' => 'Guinea', 'phone_code' => '+224'],
            ['code' => 'GP', 'name' => 'Guadalupe', 'phone_code' => '+590'],
            ['code' => 'GQ', 'name' => 'Guinea Ecuatorial', 'phone_code' => '+240'],
            ['code' => 'GR', 'name' => 'Grecia', 'phone_code' => '+30'],
            ['code' => 'GS', 'name' => 'Georgia del Sur', 'phone_code' => '+500'],
            ['code' => 'GT', 'name' => 'Guatemala', 'phone_code' => '+502'],
            ['code' => 'GU', 'name' => 'Guam', 'phone_code' => '+1671'],
            ['code' => 'GW', 'name' => 'Guinea-Bisáu', 'phone_code' => '+245'],
            ['code' => 'GY', 'name' => 'Guyana', 'phone_code' => '+592'],
            ['code' => 'HK', 'name' => 'Hong Kong', 'phone_code' => '+852'],
            ['code' => 'HM', 'name' => 'Isla Heard', 'phone_code' => '+672'],
            ['code' => 'HN', 'name' => 'Honduras', 'phone_code' => '+504'],
            ['code' => 'HR', 'name' => 'Croacia', 'phone_code' => '+385'],
            ['code' => 'HT', 'name' => 'Haití', 'phone_code' => '+509'],
            ['code' => 'HU', 'name' => 'Hungría', 'phone_code' => '+36'],
            ['code' => 'ID', 'name' => 'Indonesia', 'phone_code' => '+62'],
            ['code' => 'IE', 'name' => 'Irlanda', 'phone_code' => '+353'],
            ['code' => 'IL', 'name' => 'Israel', 'phone_code' => '+972'],
            ['code' => 'IM', 'name' => 'Isla de Man', 'phone_code' => '+44'],
            ['code' => 'IN', 'name' => 'India', 'phone_code' => '+91'],
            ['code' => 'IO', 'name' => 'Territorio Británico del Océano Índico', 'phone_code' => '+246'],
            ['code' => 'IQ', 'name' => 'Irak', 'phone_code' => '+964'],
            ['code' => 'IR', 'name' => 'Irán', 'phone_code' => '+98'],
            ['code' => 'IS', 'name' => 'Islandia', 'phone_code' => '+354'],
            ['code' => 'IT', 'name' => 'Italia', 'phone_code' => '+39'],
            ['code' => 'JE', 'name' => 'Jersey', 'phone_code' => '+44'],
            ['code' => 'JM', 'name' => 'Jamaica', 'phone_code' => '+1876'],
            ['code' => 'JO', 'name' => 'Jordania', 'phone_code' => '+962'],
            ['code' => 'JP', 'name' => 'Japón', 'phone_code' => '+81'],
            ['code' => 'KE', 'name' => 'Kenia', 'phone_code' => '+254'],
            ['code' => 'KG', 'name' => 'Kirguistán', 'phone_code' => '+996'],
            ['code' => 'KH', 'name' => 'Camboya', 'phone_code' => '+855'],
            ['code' => 'KI', 'name' => 'Kiribati', 'phone_code' => '+686'],
            ['code' => 'KM', 'name' => 'Comoras', 'phone_code' => '+269'],
            ['code' => 'KN', 'name' => 'San Cristóbal y Nieves', 'phone_code' => '+1869'],
            ['code' => 'KP', 'name' => 'Corea del Norte', 'phone_code' => '+850'],
            ['code' => 'KR', 'name' => 'Corea del Sur', 'phone_code' => '+82'],
            ['code' => 'KW', 'name' => 'Kuwait', 'phone_code' => '+965'],
            ['code' => 'KY', 'name' => 'Islas Caimán', 'phone_code' => '+1345'],
            ['code' => 'KZ', 'name' => 'Kazajistán', 'phone_code' => '+7'],
            ['code' => 'LA', 'name' => 'Laos', 'phone_code' => '+856'],
            ['code' => 'LB', 'name' => 'Líbano', 'phone_code' => '+961'],
            ['code' => 'LC', 'name' => 'Santa Lucía', 'phone_code' => '+1758'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'phone_code' => '+423'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'phone_code' => '+94'],
            ['code' => 'LR', 'name' => 'Liberia', 'phone_code' => '+231'],
            ['code' => 'LS', 'name' => 'Lesoto', 'phone_code' => '+266'],
            ['code' => 'LT', 'name' => 'Lituania', 'phone_code' => '+370'],
            ['code' => 'LU', 'name' => 'Luxemburgo', 'phone_code' => '+352'],
            ['code' => 'LV', 'name' => 'Letonia', 'phone_code' => '+371'],
            ['code' => 'LY', 'name' => 'Libia', 'phone_code' => '+218'],
            ['code' => 'MA', 'name' => 'Marruecos', 'phone_code' => '+212'],
            ['code' => 'MC', 'name' => 'Mónaco', 'phone_code' => '+377'],
            ['code' => 'MD', 'name' => 'Moldavia', 'phone_code' => '+373'],
            ['code' => 'ME', 'name' => 'Montenegro', 'phone_code' => '+382'],
            ['code' => 'MF', 'name' => 'San Martín', 'phone_code' => '+590'],
            ['code' => 'MG', 'name' => 'Madagascar', 'phone_code' => '+261'],
            ['code' => 'MH', 'name' => 'Islas Marshall', 'phone_code' => '+692'],
            ['code' => 'MK', 'name' => 'Macedonia del Norte', 'phone_code' => '+389'],
            ['code' => 'ML', 'name' => 'Malí', 'phone_code' => '+223'],
            ['code' => 'MM', 'name' => 'Birmania', 'phone_code' => '+95'],
            ['code' => 'MN', 'name' => 'Mongolia', 'phone_code' => '+976'],
            ['code' => 'MO', 'name' => 'Macao', 'phone_code' => '+853'],
            ['code' => 'MP', 'name' => 'Islas Marianas del Norte', 'phone_code' => '+1670'],
            ['code' => 'MQ', 'name' => 'Martinica', 'phone_code' => '+596'],
            ['code' => 'MR', 'name' => 'Mauritania', 'phone_code' => '+222'],
            ['code' => 'MS', 'name' => 'Montserrat', 'phone_code' => '+1664'],
            ['code' => 'MT', 'name' => 'Malta', 'phone_code' => '+356'],
            ['code' => 'MU', 'name' => 'Mauricio', 'phone_code' => '+230'],
            ['code' => 'MV', 'name' => 'Maldivas', 'phone_code' => '+960'],
            ['code' => 'MW', 'name' => 'Malaui', 'phone_code' => '+265'],
            ['code' => 'MX', 'name' => 'México', 'phone_code' => '+52'],
            ['code' => 'MY', 'name' => 'Malasia', 'phone_code' => '+60'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'phone_code' => '+258'],
            ['code' => 'NA', 'name' => 'Namibia', 'phone_code' => '+264'],
            ['code' => 'NC', 'name' => 'Nueva Caledonia', 'phone_code' => '+687'],
            ['code' => 'NE', 'name' => 'Níger', 'phone_code' => '+227'],
            ['code' => 'NF', 'name' => 'Isla Norfolk', 'phone_code' => '+672'],
            ['code' => 'NG', 'name' => 'Nigeria', 'phone_code' => '+234'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'phone_code' => '+505'],
            ['code' => 'NL', 'name' => 'Países Bajos', 'phone_code' => '+31'],
            ['code' => 'NO', 'name' => 'Noruega', 'phone_code' => '+47'],
            ['code' => 'NP', 'name' => 'Nepal', 'phone_code' => '+977'],
            ['code' => 'NR', 'name' => 'Nauru', 'phone_code' => '+674'],
            ['code' => 'NU', 'name' => 'Niue', 'phone_code' => '+683'],
            ['code' => 'NZ', 'name' => 'Nueva Zelanda', 'phone_code' => '+64'],
            ['code' => 'OM', 'name' => 'Omán', 'phone_code' => '+968'],
            ['code' => 'PA', 'name' => 'Panamá', 'phone_code' => '+507'],
            ['code' => 'PE', 'name' => 'Perú', 'phone_code' => '+51'],
            ['code' => 'PF', 'name' => 'Polinesia Francesa', 'phone_code' => '+689'],
            ['code' => 'PG', 'name' => 'Papúa Nueva Guinea', 'phone_code' => '+675'],
            ['code' => 'PH', 'name' => 'Filipinas', 'phone_code' => '+63'],
            ['code' => 'PK', 'name' => 'Pakistán', 'phone_code' => '+92'],
            ['code' => 'PL', 'name' => 'Polonia', 'phone_code' => '+48'],
            ['code' => 'PM', 'name' => 'San Pedro y Miquelón', 'phone_code' => '+508'],
            ['code' => 'PN', 'name' => 'Islas Pitcairn', 'phone_code' => '+64'],
            ['code' => 'PR', 'name' => 'Puerto Rico', 'phone_code' => '+1787'],
            ['code' => 'PS', 'name' => 'Palestina', 'phone_code' => '+970'],
            ['code' => 'PT', 'name' => 'Portugal', 'phone_code' => '+351'],
            ['code' => 'PW', 'name' => 'Palaos', 'phone_code' => '+680'],
            ['code' => 'PY', 'name' => 'Paraguay', 'phone_code' => '+595'],
            ['code' => 'QA', 'name' => 'Catar', 'phone_code' => '+974'],
            ['code' => 'RE', 'name' => 'Reunión', 'phone_code' => '+262'],
            ['code' => 'RO', 'name' => 'Rumania', 'phone_code' => '+40'],
            ['code' => 'RS', 'name' => 'Serbia', 'phone_code' => '+381'],
            ['code' => 'RU', 'name' => 'Rusia', 'phone_code' => '+7'],
            ['code' => 'RW', 'name' => 'Ruanda', 'phone_code' => '+250'],
            ['code' => 'SA', 'name' => 'Arabia Saudí', 'phone_code' => '+966'],
            ['code' => 'SB', 'name' => 'Islas Salomón', 'phone_code' => '+677'],
            ['code' => 'SC', 'name' => 'Seychelles', 'phone_code' => '+248'],
            ['code' => 'SD', 'name' => 'Sudán', 'phone_code' => '+249'],
            ['code' => 'SE', 'name' => 'Suecia', 'phone_code' => '+46'],
            ['code' => 'SG', 'name' => 'Singapur', 'phone_code' => '+65'],
            ['code' => 'SH', 'name' => 'Santa Elena', 'phone_code' => '+290'],
            ['code' => 'SI', 'name' => 'Eslovenia', 'phone_code' => '+386'],
            ['code' => 'SJ', 'name' => 'Svalbard y Jan Mayen', 'phone_code' => '+47'],
            ['code' => 'SK', 'name' => 'Eslovaquia', 'phone_code' => '+421'],
            ['code' => 'SL', 'name' => 'Sierra Leona', 'phone_code' => '+232'],
            ['code' => 'SM', 'name' => 'San Marino', 'phone_code' => '+378'],
            ['code' => 'SN', 'name' => 'Senegal', 'phone_code' => '+221'],
            ['code' => 'SO', 'name' => 'Somalia', 'phone_code' => '+252'],
            ['code' => 'SR', 'name' => 'Surinam', 'phone_code' => '+597'],
            ['code' => 'SS', 'name' => 'Sudán del Sur', 'phone_code' => '+211'],
            ['code' => 'ST', 'name' => 'Santo Tomé y Príncipe', 'phone_code' => '+239'],
            ['code' => 'SV', 'name' => 'El Salvador', 'phone_code' => '+503'],
            ['code' => 'SX', 'name' => 'Sint Maarten', 'phone_code' => '+1721'],
            ['code' => 'SY', 'name' => 'Siria', 'phone_code' => '+963'],
            ['code' => 'SZ', 'name' => 'Esuatini', 'phone_code' => '+268'],
            ['code' => 'TC', 'name' => 'Islas Turcas y Caicos', 'phone_code' => '+1649'],
            ['code' => 'TD', 'name' => 'Chad', 'phone_code' => '+235'],
            ['code' => 'TF', 'name' => 'Territorios Australes Franceses', 'phone_code' => '+262'],
            ['code' => 'TG', 'name' => 'Togo', 'phone_code' => '+228'],
            ['code' => 'TH', 'name' => 'Tailandia', 'phone_code' => '+66'],
            ['code' => 'TJ', 'name' => 'Tayikistán', 'phone_code' => '+992'],
            ['code' => 'TK', 'name' => 'Tokelau', 'phone_code' => '+690'],
            ['code' => 'TL', 'name' => 'Timor Oriental', 'phone_code' => '+670'],
            ['code' => 'TM', 'name' => 'Turkmenistán', 'phone_code' => '+993'],
            ['code' => 'TN', 'name' => 'Túnez', 'phone_code' => '+216'],
            ['code' => 'TO', 'name' => 'Tonga', 'phone_code' => '+676'],
            ['code' => 'TR', 'name' => 'Turquía', 'phone_code' => '+90'],
            ['code' => 'TT', 'name' => 'Trinidad y Tobago', 'phone_code' => '+1868'],
            ['code' => 'TV', 'name' => 'Tuvalu', 'phone_code' => '+688'],
            ['code' => 'TW', 'name' => 'Taiwán', 'phone_code' => '+886'],
            ['code' => 'TZ', 'name' => 'Tanzania', 'phone_code' => '+255'],
            ['code' => 'UA', 'name' => 'Ucrania', 'phone_code' => '+380'],
            ['code' => 'UG', 'name' => 'Uganda', 'phone_code' => '+256'],
            ['code' => 'UM', 'name' => 'Islas Menores de Estados Unidos', 'phone_code' => '+1'],
            ['code' => 'US', 'name' => 'Estados Unidos', 'phone_code' => '+1'],
            ['code' => 'UY', 'name' => 'Uruguay', 'phone_code' => '+598'],
            ['code' => 'UZ', 'name' => 'Uzbekistán', 'phone_code' => '+998'],
            ['code' => 'VA', 'name' => 'Ciudad del Vaticano', 'phone_code' => '+39'],
            ['code' => 'VC', 'name' => 'San Vicente y las Granadinas', 'phone_code' => '+1784'],
            ['code' => 'VE', 'name' => 'Venezuela', 'phone_code' => '+58'],
            ['code' => 'VG', 'name' => 'Islas Vírgenes Británicas', 'phone_code' => '+1284'],
            ['code' => 'VI', 'name' => 'Islas Vírgenes de Estados Unidos', 'phone_code' => '+1340'],
            ['code' => 'VN', 'name' => 'Vietnam', 'phone_code' => '+84'],
            ['code' => 'VU', 'name' => 'Vanuatu', 'phone_code' => '+678'],
            ['code' => 'WF', 'name' => 'Wallis y Futuna', 'phone_code' => '+681'],
            ['code' => 'WS', 'name' => 'Samoa', 'phone_code' => '+685'],
            ['code' => 'YE', 'name' => 'Yemen', 'phone_code' => '+967'],
            ['code' => 'YT', 'name' => 'Mayotte', 'phone_code' => '+262'],
            ['code' => 'ZA', 'name' => 'Sudáfrica', 'phone_code' => '+27'],
            ['code' => 'ZM', 'name' => 'Zambia', 'phone_code' => '+260'],
            ['code' => 'ZW', 'name' => 'Zimbabue', 'phone_code' => '+263'],
        ];

        return response()->json([
            'success' => true,
            'countries' => $countries,
            'total' => count($countries)
        ]);
    }

    /**
     * Busca países por nombre o código
     */
    public function search(Request $request): JsonResponse
    {
        $query = $request->input('q', '');

        if (empty($query)) {
            return $this->index();
        }

        $allCountries = $this->index()->getData()->countries;

        $filtered = array_filter($allCountries, function($country) use ($query) {
            return stripos($country->name, $query) !== false ||
                   stripos($country->code, $query) !== false ||
                   stripos($country->phone_code, $query) !== false;
        });

        return response()->json([
            'success' => true,
            'countries' => array_values($filtered),
            'total' => count($filtered),
            'query' => $query
        ]);
    }
}
